"""add assigned_by attribute in work_order table

Revision ID: b911cbaf92a5
Revises: d3204c88eb7d
Create Date: 2026-07-29 16:55:06.888835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b911cbaf92a5'
down_revision = 'd3204c88eb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_by')

    # ### end Alembic commands ###
